"""extend_checklist_item_and_add_extracted_financial_value

Revision ID: 0143e667172c
Revises: d378b492aad8
Create Date: 2026-06-23 12:41:18.080836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0143e667172c'
down_revision: Union[str, Sequence[str], None] = 'd378b492aad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_financial_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_job_id', sa.Integer(), nullable=False),
    sa.Column('job_file_id', sa.Integer(), nullable=True),
    sa.Column('value_key', sa.String(length=100), nullable=False),
    sa.Column('value_label', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('period_type', sa.String(length=50), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_file_id'], ['job_files.id'], ),
    sa.ForeignKeyConstraint(['tax_job_id'], ['tax_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_financial_values_id'), 'extracted_financial_values', ['id'], unique=False)
    op.add_column('checklist_items', sa.Column('rule_id', sa.String(length=50), nullable=True))
    op.add_column('checklist_items', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('checklist_items', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('checklist_items', sa.Column('extracted_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('checklist_items', sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('checklist_items', sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('checklist_items', sa.Column('tolerance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('checklist_items', sa.Column('missing_support', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_items', 'missing_support')
    op.drop_column('checklist_items', 'tolerance')
    op.drop_column('checklist_items', 'difference')
    op.drop_column('checklist_items', 'expected_amount')
    op.drop_column('checklist_items', 'extracted_amount')
    op.drop_column('checklist_items', 'confidence_score')
    op.drop_column('checklist_items', 'category')
    op.drop_column('checklist_items', 'rule_id')
    op.drop_index(op.f('ix_extracted_financial_values_id'), table_name='extracted_financial_values')
    op.drop_table('extracted_financial_values')
    # ### end Alembic commands ###
